import './globals.css'
import "slick-carousel/slick/slick.css";
import { Header } from './components/Header'
import Footer from "./components/Footer";
import "slick-carousel/slick/slick-theme.css";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Header />
      <body>{children}</body>
      <Footer/>
    </html>
  )
}
